ALTER TABLE REZERWACJA DROP FOREIGN KEY FK_REZERWACJA_M_WYCIECZKA_ID_WYCIECZKI
ALTER TABLE UCZESTNICTWO DROP FOREIGN KEY FK_UCZESTNICTWO_M_REZERWACJA_ID_REZERWACJI
ALTER TABLE KATALOG_CENNIK DROP FOREIGN KEY FK_KATALOG_CENNIK_m_Cennik_ID_CENNIK
ALTER TABLE KATALOG_CENNIK DROP FOREIGN KEY FK_KATALOG_CENNIK_Katalog_ID_KATALOG
ALTER TABLE KATALOG_WYCIECZKA DROP FOREIGN KEY FK_KATALOG_WYCIECZKA_m_Wycieczka_ID_WYCIECZKI
ALTER TABLE KATALOG_WYCIECZKA DROP FOREIGN KEY FK_KATALOG_WYCIECZKA_Katalog_ID_KATALOG
DROP TABLE CENNIK
DROP TABLE KATALOG
DROP TABLE REZERWACJA
DROP TABLE UCZESTNICTWO
DROP TABLE WYCIECZKA
DROP TABLE KATALOG_CENNIK
DROP TABLE KATALOG_WYCIECZKA
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
